import './globals.css'
import { Inter } from 'next/font/google'
import 'primeicons/primeicons.css';
import "primereact/resources/themes/lara-light-indigo/theme.css"
import "primereact/resources/primereact.min.css";   
import "bootstrap/dist/css/bootstrap.min.css"

// Global importlar burada.

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// JSX
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
