import './globals.css';
import { Inter } from 'next/font/google';
import 'primeicons/primeicons.css';
import 'primereact/resources/themes/lara-light-indigo/theme.css';
import 'primereact/resources/primereact.min.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import { AuthContext, AuthProvider } from './contexts/AuthContext';
import Navbar from './components/navbar/Navbar';
import Subscriber from './components/subscriber/Subscriber';
import { LoaderProvider } from './contexts/LoaderContext';
// Global importlar burada.

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};
// JSX
export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <LoaderProvider>
                    <AuthProvider>
                        <Subscriber />
                        <Navbar></Navbar>
                        {children}
                    </AuthProvider>
                </LoaderProvider>
            </body>
        </html>
    );
}
